import { InferGetStaticPropsType } from 'next'
import { CaretRightFill, EnvelopeFill, Github, LightbulbFill, Slack, Twitter } from 'react-bootstrap-icons';
import Button from 'react-bootstrap/Button';
import Card from 'react-bootstrap/Card';
import Badge from 'react-bootstrap/Badge';
import CardGroup from 'react-bootstrap/CardGroup';
import ButtonGroup from 'react-bootstrap/ButtonGroup';

import Layout from '../components/Layout'
import Content from '../components/Content'
import { Summary } from '../components/util';
import { getStaticContentProps } from '../lib/content'
import Link from 'next/link';

const TITLE = 'Licensing OpenSanctions';
const SUMMARY = 'Our objective is to continually release high-quality '
  + 'persons of interest data as a resource for business and civil society. '
  + 'In order to make this sustainable, we\'re asking for-profit '
  + 'users to support the project and obtain a license.';

export default function Licensing({ content }: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <Layout.Content content={content}>
      <Content.Menu title={TITLE}>
        <Summary summary={SUMMARY} />
        <div className="text-body">
          <CardGroup className="pricing">
            <Card bg="secondary" text="white">
              <Card.Body>
                <Card.Title>
                  Sanctions bulk data<br />
                  <Badge bg="primary">$<span className="num">395</span>/mo</Badge>
                </Card.Title>
                <Card.Text>
                  Consolidated sanctions and crime
                  data (updated daily). License covers any in-house use of the
                  data, and as an embedded resource in products and services sold to
                  third parties.
                </Card.Text>
              </Card.Body>
              <Card.Footer>
                <ButtonGroup>
                  <Button href="/docs/commercial-faq/" variant="light">
                    <LightbulbFill className="bsIcon" />
                    Learn more
                  </Button>
                  <Button href="/contact/" variant="primary">
                    <EnvelopeFill className="bsIcon" />
                    Contact us
                  </Button>
                </ButtonGroup>
                <div className="buy-now">
                  Sound good? <Link href="https://buy.stripe.com/5kAdRNad3fmhg6ceV4">Subscribe now</Link>.
                </div>
              </Card.Footer>
            </Card>
            <Card bg="primary" text="white">
              <Card.Body>
                <Card.Title>
                  Sanctions and PEPs data<br />
                  <Badge bg="light">$<span className="num">595</span>/mo</Badge>
                </Card.Title>
                <Card.Text>
                  Consolidated sanctions and crime bulk data, plus politically
                  exposed persons (PEP) lists generated by the Peppercat
                  project (World Leaders and Legislators).
                </Card.Text>
              </Card.Body>
              <Card.Footer>
                <ButtonGroup>
                  <Button href="/docs/commercial-faq/" variant="light">
                    <LightbulbFill className="bsIcon" />
                    Learn more
                  </Button>
                  <Button href="/contact/" variant="secondary">
                    <EnvelopeFill className="bsIcon" />
                    Contact us
                  </Button>
                </ButtonGroup>
                <div className="buy-now">
                  We've got a deal? <Link href="https://buy.stripe.com/14kfZV5WN8XT9HO28j">Subscribe now</Link>.
                </div>
              </Card.Footer>
            </Card>
            <Card bg="secondary" text="white">
              <Card.Body>
                <Card.Title>
                  Flat-rate API usage<br />
                  <Badge bg="primary">$<span className="num">695</span>/mo</Badge>
                </Card.Title>
                <Card.Text>
                  Service contract for the use of api.opensanctions.org to conduct automated
                  entity lookups and multi-attribute matching. Includes 300,000 requests per
                  month.
                </Card.Text>
              </Card.Body>
              <Card.Footer>
                <ButtonGroup>
                  <Button href="/docs/commercial-faq/" variant="light">
                    <LightbulbFill className="bsIcon" />
                    Learn more
                  </Button>
                  <Button href="/contact/" variant="primary">
                    <EnvelopeFill className="bsIcon" />
                    Contact us
                  </Button>
                </ButtonGroup>
                <div className="buy-now">
                  In a hurry? <a href="https://buy.stripe.com/8wM151fxn6PL4nu7sF">Subscribe now</a>.
                </div>
              </Card.Footer>
            </Card>
          </CardGroup>
          <p>
            <strong>Not ideal for you?</strong> OpenSanctions
            provides <strong><Link href="/docs/commercial-faq/#exemptions">licensing exemptions
              for journalists and activists</Link></strong>. Even beyond that, we're committed
            to make this data available to everyone. If the licensing is stopping you from using our
            OpenSanctions, <Link href="/contact/">contact us</Link> and we'll fix it.
          </p>
        </div>
      </Content.Menu>
    </Layout.Content >
  )
}

export const getStaticProps = getStaticContentProps('licensing')
