import { InferGetStaticPropsType } from 'next';
import { EnvelopeFill, LightbulbFill } from 'react-bootstrap-icons';
import Button from 'react-bootstrap/Button';
import Card from 'react-bootstrap/Card';
import Badge from 'react-bootstrap/Badge';
import CardGroup from 'react-bootstrap/CardGroup';
import ButtonGroup from 'react-bootstrap/ButtonGroup';

import Layout from '../components/Layout'
import Content from '../components/Content'
import { Numeric, Summary } from '../components/util';
import Link from 'next/link';
import { getDatasets } from '../lib/data';

import styles from '../styles/Licensing.module.scss'

const TITLE = 'Licensing OpenSanctions';
const SUMMARY = 'We provide a fully auditable, high-quality database for '
  + 'open source intelligence. This includes carefully cleaned and de-duplicated '
  + 'entities that are subject to manual review. The use of this data for any '
  + 'business purposes requires a licensing agreement.';

export default function Licensing({ sanctions_count, default_count }: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <Layout.Base title={TITLE} description={SUMMARY}>
      <Content.Menu title={TITLE}>
        <Summary summary={SUMMARY} />
        <div className="text-body">
          <CardGroup className={styles.pricingPanel}>
            <Card className={styles.firstColumn} text="white">
              <Card.Body>
                <Card.Title>
                  Sanctions bulk data<br />
                  <Badge bg="light">
                    <span className="num"><Numeric value={sanctions_count} /></span> targets
                  </Badge>
                </Card.Title>
                <Card.Text>
                  Consolidated sanctions and crime
                  data (updated daily). License covers any in-house use of the
                  data, and as an embedded resource in products and services sold to
                  third parties.
                </Card.Text>
              </Card.Body>
              <Card.Footer>
                <ButtonGroup>
                  <Button href="/docs/commercial-faq/#tiers" variant="light">
                    <LightbulbFill className="bsIcon" />
                    Learn more
                  </Button>
                  <Button href="/contact/" variant="secondary">
                    <EnvelopeFill className="bsIcon" />
                    Contact us
                  </Button>
                </ButtonGroup>
                {/* <div className="buy-now">
                  Sound good? <Link href="https://buy.stripe.com/5kAdRNad3fmhg6ceV4">Subscribe now</Link>.
                </div> */}
              </Card.Footer>
            </Card>
            <Card className={styles.secondColumn} text="white">
              <Card.Body>
                <Card.Title>
                  Sanctions and PEPs data<br />
                  <Badge bg="light">
                    <span className="num"><Numeric value={default_count} /></span> targets
                  </Badge>
                </Card.Title>
                <Card.Text>
                  Consolidated sanctions and crime bulk data, plus politically
                  exposed persons (PEP) lists generated by the Peppercat
                  project (World Leaders and Legislators).
                </Card.Text>
              </Card.Body>
              <Card.Footer>
                <ButtonGroup>
                  <Button href="/docs/commercial-faq/#tiers" variant="light">
                    <LightbulbFill className="bsIcon" />
                    Learn more
                  </Button>
                  <Button href="/contact/" variant="secondary">
                    <EnvelopeFill className="bsIcon" />
                    Contact us
                  </Button>
                </ButtonGroup>
                {/* <div className="buy-now">
                  We've got a deal? <Link href="https://buy.stripe.com/14kfZV5WN8XT9HO28j">Subscribe now</Link>.
                </div> */}
              </Card.Footer>
            </Card>
            <Card className={styles.thirdColumn} text="white">
              <Card.Body>
                <Card.Title>
                  Flat-rate API usage<br />
                  <Badge bg="light">
                    <span className="num">300,000</span> req/mo
                  </Badge>
                </Card.Title>
                <Card.Text>
                  Service contract for the use of api.opensanctions.org to conduct automated
                  entity lookups and multi-attribute matching. Includes 300,000 requests per
                  month.
                </Card.Text>
              </Card.Body>
              <Card.Footer>
                <ButtonGroup>
                  <Button href="/docs/commercial-faq/#tiers" variant="light">
                    <LightbulbFill className="bsIcon" />
                    Learn more
                  </Button>
                  <Button href="/contact/" variant="secondary">
                    <EnvelopeFill className="bsIcon" />
                    Contact us
                  </Button>
                </ButtonGroup>
                {/* <div className="buy-now">
                  In a hurry? <a href="https://buy.stripe.com/8wM151fxn6PL4nu7sF">Subscribe now</a>.
                </div> */}
              </Card.Footer>
            </Card>
          </CardGroup>
          <p>
            <strong>Not ideal for you?</strong> OpenSanctions
            provides <strong><Link href="/docs/commercial-faq/#exemptions">licensing exemptions
              for journalists and activists</Link></strong>. And beyond that, we're committed
            to make this data available to everyone. If the licensing is stopping you from using
            OpenSanctions, <Link href="/contact/">contact us</Link> and we'll fix it.
          </p>
          <p>
            <strong>Got more questions?</strong> Check out the <Link href="/docs/commercial-faq/">Commercial use FAQ</Link>
          </p>
        </div>
      </Content.Menu>
    </Layout.Base >
  )
}


export const getStaticProps = async () => {
  const datasets = await getDatasets();
  const sanctions = datasets.find(d => d.name === 'sanctions');
  const default_ = datasets.find(d => d.name === 'default');
  return {
    props: {
      sanctions_count: sanctions?.target_count || 25000,
      default_count: default_?.target_count || 25000,
    }
  }
}
